### ISSUE TITLE
Non blocking read or loop data examples?

### ISSUE THREAD

**Issue by Jae-hyun** [commtech/synccom-windows#1]
Hello, I'm newbie on synccom device.

Is there Non blocking read or loop data receive examples?
(I'm not familiar with win32 api.)

I've already run the tutorial.c example but works only blocking mode.
(blocking with timeout or any cancel method to read?)

Thanks.

**Comment by jdroney** [comment]
Hello!

To read without blocking, you can use Overlapped structures and WaitForSingleObject:
https://docs.microsoft.com/en-us/windows/win32/sync/synchronization-and-overlapped-input-and-output

Typically, the handle is opened with FILE_FLAG_OVERLAPPED, an overlapped structure is initialized with CreateEvent(), and then that structure is passed into ReadFile(). The ReadFile() will immediately return, and you can use WaitForSingleObject() and GetOverlappedResult() to determine the next steps.

Josh
