### ISSUE TITLE
Many IOCTL codes falsely return incorrect function

### ISSUE THREAD

**Issue by dknueven** [commtech/synccom-windows#2]
In Port.c in function SyncComEvtIoDeviceControl, IOCTL codes SYNCCOM_ENABLE_APPEND_STATUS, SYNCCOM_DISABLE_APPEND_STATUS, SYNCCOM_ENABLE_APPEND_TIMESTAMP, SYNCCOM_DISABLE_APPEND_TIMESTAMP, SYNCCOM_ENABLE_RX_MULTIPLE, SYNCCOM_DISABLE_RX_MULTIPLE, SYNCCOM_ENABLE_IGNORE_TIMEOUT, SYNCCOM_DISABLE_IGNORE_TIMEOUT all leave status at it's default value of STATUS_INVALID_DEVICE_REQUEST.

**Comment by jdroney** [comment]
Good eye. I can't believe I overlooked that. I'll get that fixed in the next release.

**Comment by dknueven** [comment]
Thanks!
